apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: cnpg-templates
spec:
  type: url
  targets:
    - https://raw.githubusercontent.com/callmewhatuwant/backstage-test/main/template.yaml
