apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: cnpg-templates
spec:
  - type: url
    target: https://raw.githubusercontent.com/callmewhatuwant/backstage-test/refs/heads/main/cnpg-cluster.yaml
  - type: url
    target: https://raw.githubusercontent.com/callmewhatuwant/backstage-test/refs/heads/main/test.yaml
  
