apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cnpg-postgres
  title: CNPG PostgreSQL Cluster
  description: Generate CNPG YAML and publish to GitHub

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basis
      required: [name, namespace]
      properties:
        name:
          type: string
          default: test
        namespace:
          type: string
          default: test

    - title: Database
      required: [database, owner]
      properties:
        database:
          type: string
          default: test
        owner:
          type: string
          default: test

    - title: Ressourcen
      required: [instances, size]
      properties:
        instances:
          type: number
          default: 2
        size:
          type: string
          default: 1Gi

  steps:
    - id: generate
      name: Generate CNPG YAML
      action: fetch:template
      input:
        url: github.com?owner=callmewhatuwant&repo=backstage-test&branch=main&path=skeleton
        targetPath: .

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=callmewhatuwant&repo={{ name }}-cnpg
        description: CNPG PostgreSQL cluster {{ name }}
        defaultBranch: main

  output:
    links:
      - title: Open GitHub Repository
        url: "{{ steps.publish.output.remoteUrl }}"
