apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cnpg-postgres
  title: CNPG PostgreSQL Cluster
  description: PostgreSQL Cluster for CloudNativePG
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basis
      required: [name, namespace]
      properties:
        name:
          type: string
          title: Cluster Name
          default: test
        namespace:
          type: string
          title: Namespace
          default: test

    - title: Database
      required: [database, owner]
      properties:
        database:
          type: string
          title: Database Name
          default: test
        owner:
          type: string
          title: Database Owner
          default: test

    - title: Ressourcen
      required: [instances, size]
      properties:
        instances:
          type: number
          title: Instances
          default: 2
        size:
          type: string
          title: Storage Size
          default: 1Gi

  steps:
    - id: generate
      name: Generate CNPG YAML
      action: fetch:template
      input:
        url: github.com?owner=callmewhatuwant&repo=backstage-test&branch=main&path=skeleton
        targetPath: .
  output:
    text:
      - title: Generated CNPG YAML
        content: |
          {{ steps.generate.output.files['postgres-cluster.yaml'] }}
