apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cnpg-postgres
  title: CNPG PostgreSQL Cluster
  description: PostgreSQL Cluster for CloudNativePG
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basis
      required: [name, namespace]
      properties:
        name:
          type: string
          title: Cluster Name
        namespace:
          type: string
          title: Namespace

    - title: Database
      required: [database, owner]
      properties:
        database:
          type: string
          title: Database Name
        owner:
          type: string
          title: Database Owner

    - title: Ressourcen
      required: [instances, size]
      properties:
        instances:
          type: number
          title: Instances
          default: 2
        size:
          type: string
          title: Storage Size
          default: 1Gi

  steps:
    - id: generate
      name: Generate CNPG YAML
      action: fetch:template
      input:
        url: github.com?owner=callmewhatuwant&repo=backstage-test&branch=main&path=skeleton
        targetPath: .
      
  output:
    links:
      - title: Download CNPG YAML
        url: /api/scaffolder/v2/tasks/{{ task.id }}/files/postgres-cluster.yaml
