apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cnpg-postgres
  title: CNPG PostgreSQL Cluster
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basis
      required: [name, namespace]
      properties:
        name:
          type: string
        namespace:
          type: string

    - title: Database
      required: [database, owner]
      properties:
        database:
          type: string
        owner:
          type: string

    - title: Ressourcen
      required: [instances, size]
      properties:
        instances:
          type: number
        size:
          type: string

  steps:
    - id: generate
      action: fetch:template
      input:
        url: github.com?owner=callmewhatuwant&repo=backstage-test&branch=main&path=skeleton
        targetPath: ./output

    - id: publish
      action: publish:github
      input:
        repoUrl: github.com?owner=callmewhatuwant&repo=cnpg-clusters
        description: Generated CNPG YAML
        defaultBranch: main

  output:
    links:
      - title: Open GitHub Repository
        url: https://github.com/callmewhatuwant/{{ parameters.name }}-cnpg
