apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cnpg-postgres
  title: CNPG PostgreSQL Cluster
  description: PostgreSQL Cluster for CloudNativePG

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basis
      required: [name, namespace]
      properties:
        name:
          type: string
          default: test
        namespace:
          type: string
          default: test

    - title: Database
      required: [database, owner]
      properties:
        database:
          type: string
          default: test
        owner:
          type: string
          default: test

    - title: Ressourcen
      required: [instances, size]
      properties:
        instances:
          type: number
          default: 2
        size:
          type: string
          default: 1Gi

  steps:
    - id: generate
      name: Generate CNPG YAML
      action: fetch:template
      input:
        url: github.com?owner=callmewhatuwant&repo=backstage-test&branch=main&path=skeleton
        targetPath: .

    - id: read
      name: Read generated YAML
      action: fs:read
      input:
        path: postgres-cluster.yaml

  output:
    text:
      - title: Generated CNPG YAML
        content: |
          {{ steps.read.output.content }}
