apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cnpg-debug-inline
  title: CNPG Inline Debug
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basis
      required: [name, namespace]
      properties:
        name:
          type: string
          default: test
        namespace:
          type: string
          default: test

    - title: Database
      required: [database, owner]
      properties:
        database:
          type: string
          default: test
        owner:
          type: string
          default: test

    - title: Ressourcen
      required: [instances, size]
      properties:
        instances:
          type: number
          default: 2
        size:
          type: string
          default: 1Gi

  steps:
    - id: debug
      action: debug:log
      input:
        message: |-
    
          ===== RENDERED CNPG CLUSTER =====
    
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
            name: ${{ parameters.name }}
            namespace: ${{ parameters.namespace }}
          spec:
            instances: ${{ parameters.instances }}
            storage:
              size: ${{ parameters.size }}
            bootstrap:
              initdb:
                database: ${{ parameters.database }}
                owner: ${{ parameters.owner }}
    
          ===== END =====
