apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cnpg-postgres
  title: CNPG PostgreSQL Cluster
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basis
      required: [name, namespace]
      properties:
        name:
          type: string
          title: Cluster Name
          default: test
        namespace:
          type: string
          title: Namespace
          default: test

    - title: Database
      required: [database, owner]
      properties:
        database:
          type: string
          title: Database Name
          default: test
        owner:
          type: string
          title: Database Owner
          default: test

    - title: Ressourcen
      required: [instances, size]
      properties:
        instances:
          type: number
          title: Instances
          default: 2
        size:
          type: string
          title: Storage Size
          default: 1Gi

  steps:
    - id: generate
      action: fetch:template
      input:
        url: github.com?owner=callmewhatuwant&repo=backstage-test&branch=main

    - id: publish
      action: publish:github
      input:
        repoUrl: github.com?owner=callmewhatuwant&repo=cnpg-clusters
        description: Generated CNPG YAML
        defaultBranch: main

  output:
    links:
      - title: Open GitHub Repository
        url: https://github.com/callmewhatuwant/repo=cnpg-clusters
